name: Netlify Deploy
on:
  pull_request:
    branches:
      - main
      - development
    types: [closed]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node Init
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Netlify
        run: |
          npm install netlify-cli -g \
          npm install @netlify/plugin-nextjs -g

      - name: Install Dependencies
        run: npm ci

      - name: Deploy to Netlify Preview
        if: ${{ success() && github.ref_name == 'development' }}
        run: |
          netlify deploy --build \
          --site ${{ secrets.NETLIFY_SITE_ID }} \
          --auth ${{ secrets.NETLIFY_DEPLOY_KEY }} \
          --message "${{ github.event.pull_request.title }}"

      - name: Deploy to Netlify Production
        if: ${{ success() && github.ref_name == 'main' }}
        run: |
          netlify deploy --build \
          --site ${{ secrets.NETLIFY_SITE_ID }} \
          --auth ${{ secrets.NETLIFY_DEPLOY_KEY }} \
          --message "${{ github.event.pull_request.title }}" \
          --prod

