name: Netlify Deploy
on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node Init
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Netlify
        run: npm install netlify-cli -g

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Netlify
        if: success()
        run: |
          netlify deploy \
          --dir build \
          --site ${{ secrets.NETLIFY_SITE_ID }} \
          --auth ${{ secrets.NETLIFY_DEPLOY_KEY }} \
          --prod
