name: Netlify Deploy
on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths-ignore:
      - '*.md'
      - '.github/*'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node Init
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Netlify
        run: |
          npm install netlify-cli -g \
          npm install @netlify/plugin-nextjs

      - name: Install Dependencies
        run: npm ci

      - name: Deploy to Netlify
        if: ${{ success() }}
        run: |
          netlify deploy --build \
          --dir build \
          --site ${{ secrets.NETLIFY_SITE_ID }} \
          --auth ${{ secrets.NETLIFY_DEPLOY_KEY }} \
          --prod
