name: Netlify Deploy
on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: rentalreviews
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node Init
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Netlify
        run: |
          npm install netlify-cli -g \
          npm install @netlify/plugin-nextjs -g

#      - name: Create Test Env File
#        uses: tmshkr/handle-env@v1.2
#        if: ${{ github.ref_name == 'development' }}
#        with:
#          env: |
#            DB_ENV='test'
#            CACHE_TTL=${{ vars.CACHE_TTL }}
#            FIREBASE_STAGING_STAGING_API_KEY=${{ vars.FIREBASE_STAGING_STAGING_API_KEY }}
#            FIREBASE_STAGING_AUTH_DOMAIN=${{ vars.FIREBASE_STAGING_AUTH_DOMAIN }}
#            FIREBASE_STAGING_PROJECT_ID=${{ vars.FIREBASE_STAGING_PROJECT_ID }}
#            FIREBASE_STAGING_STORAGE_BUCKET=${{ vars.FIREBASE_STAGING_STORAGE_BUCKET }}
#            FIREBASE_STAGING_MESSAGING_SENDER_ID=${{ vars.FIREBASE_STAGING_MESSAGING_SENDER_ID }}
#            FIREBASE_STAGING_APP_ID=${{ vars.FIREBASE_STAGING_APP_ID }}

      - name: Create Production Env File
        uses: tmshkr/handle-env@v1.2
        if: ${{ github.ref_name == 'main' }}
        with:
          env: |
            DB_ENV='production'
            CACHE_TTL=${{ vars.CACHE_TTL }}
            FIREBASE_API_KEY=${{ vars.FIREBASE_API_KEY }}
            FIREBASE_AUTH_DOMAIN=${{ vars.FIREBASE_AUTH_DOMAIN }}
            FIREBASE_PROJECT_ID=${{ vars.FIREBASE_PROJECT_ID }}
            FIREBASE_STORAGE_BUCKET=${{ vars.FIREBASE_STORAGE_BUCKET }}
            FIREBASE_MESSAGING_SENDER_ID=${{ vars.FIREBASE_MESSAGING_SENDER_ID }}
            FIREBASE_APP_ID=${{ vars.FIREBASE_APP_ID }}
            FIREBASE_MEASUREMENT_ID=${{ vars.FIREBASE_MEASUREMENT_ID }}
          

      - name: Install Dependencies
        run: npm ci

#      - name: Deploy to Netlify Preview
#        if: ${{ success() && github.ref_name == 'development' }}
#        run: |
#          netlify deploy --build \
#          --site ${{ secrets.NETLIFY_SITE_ID }} \
#          --auth ${{ secrets.NETLIFY_DEPLOY_KEY }} \
#          --message "${{ github.event.pull_request.title }}"

      - name: Deploy to Netlify Production
        if: ${{ success() && github.ref_name == 'main' }}
        run: |
          netlify deploy --build \
          --site ${{ secrets.NETLIFY_SITE_ID }} \
          --auth ${{ secrets.NETLIFY_DEPLOY_KEY }} \
          --message "${{ github.event.pull_request.title }}" \
          --prod

